In [90]:
import pandas as pd
import numpy as np

In [91]:
df= pd.read_csv('Placement_Data_Full_Class.csv')

In [92]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sl_no           215 non-null    int64
 1   gender          215 non-null    object
 2   ssc_p           215 non-null    float64
 3   ssc_b           215 non-null    object
 4   hsc_p           215 non-null    float64
 5   hsc_b           215 non-null    object
 6   hsc_s           215 non-null    object
 7   degree_p        215 non-null    float64
 8   degree_t        215 non-null    object
 9   workex          215 non-null    object
 10  etest_p         215 non-null    float64
 11  specialisation  215 non-null    object
 12  mba_p           215 non-null    float64
 13  status          215 non-null    object
 14  salary          148 non-null    float64
dtypes: float64(6), int64(1), object(8)
memory usage: 25.3+ KB

In [93]:
df.columns

Index(['sl_no', 'gender', 'ssc_p', 'ssc_b', 'hsc_p', 'hsc_b', 'hsc_s',
       'degree_p', 'degree_t', 'workex', 'etest_p', 'specialisation', 'mba_p',
       'status', 'salary'],
      dtype='object')

In [94]:
df.tail()

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
210,211,M,80.6,Others,82.0,Others,Commerce,77.6,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.0,Others,60.0,Others,Science,72.0,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.0,Others,67.0,Others,Commerce,73.0,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.0,Others,66.0,Others,Commerce,58.0,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.0,Central,58.0,Others,Science,53.0,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

In [95]:
df.isnull().sum()

sl_no              0
gender             0
ssc_p              0
ssc_b              0
hsc_p              0
hsc_b              0
hsc_s              0
degree_p           0
degree_t           0
workex             0
etest_p            0
specialisation     0
mba_p              0
status             0
salary            67
dtype: int64

In [96]:
df.dtypes

sl_no               int64
gender             object
ssc_p             float64
ssc_b              object
hsc_p             float64
hsc_b              object
hsc_s              object
degree_p          float64
degree_t           object
workex             object
etest_p           float64
specialisation     object
mba_p             float64
status             object
salary            float64
dtype: object

In [97]:
df.dropna()

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
7,8,M,82.00,Central,64.00,Central,Science,66.00,Sci&Tech,Yes,67.0,Mkt&Fin,62.14,Placed,252000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,210,M,62.00,Central,72.00,Central,Commerce,65.00,Comm&Mgmt,No,67.0,Mkt&Fin,56.49,Placed,216000.0
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0

In [98]:
df.drop_duplicates()

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

In [99]:
df.dtypes

sl_no               int64
gender             object
ssc_p             float64
ssc_b              object
hsc_p             float64
hsc_b              object
hsc_s              object
degree_p          float64
degree_t           object
workex             object
etest_p           float64
specialisation     object
mba_p             float64
status             object
salary            float64
dtype: object

In [100]:
df.drop('sl_no', axis=1, inplace=True)

In [101]:
df.drop('gender', axis=1, inplace=True)

In [102]:
df.head()

,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0

In [103]:
df.columns

Index(['ssc_p', 'ssc_b', 'hsc_p', 'hsc_b', 'hsc_s', 'degree_p', 'degree_t',
       'workex', 'etest_p', 'specialisation', 'mba_p', 'status', 'salary'],
      dtype='object')

In [104]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ssc_p           215 non-null    float64
 1   ssc_b           215 non-null    object
 2   hsc_p           215 non-null    float64
 3   hsc_b           215 non-null    object
 4   hsc_s           215 non-null    object
 5   degree_p        215 non-null    float64
 6   degree_t        215 non-null    object
 7   workex          215 non-null    object
 8   etest_p         215 non-null    float64
 9   specialisation  215 non-null    object
 10  mba_p           215 non-null    float64
 11  status          215 non-null    object
 12  salary          148 non-null    float64
dtypes: float64(6), object(7)
memory usage: 22.0+ KB

In [105]:
df.describe()

,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
count,215.000000,215.000000,215.000000,215.000000,215.000000,148.000000
mean,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
std,10.827205,10.897509,7.358743,13.275956,5.833385,93457.452420
min,40.890000,37.000000,50.000000,50.000000,51.210000,200000.000000
25%,60.600000,60.900000,61.000000,60.000000,57.945000,240000.000000
50%,67.000000,65.000000,66.000000,71.000000,62.000000,265000.000000
75%,75.700000,73.000000,72.000000,83.500000,66.255000,300000.000000
max,89.400000,97.700000,91.000000,98.000000,77.890000,940000.000000

In [106]:
df.head()

,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0

In [107]:
df.columns

Index(['ssc_p', 'ssc_b', 'hsc_p', 'hsc_b', 'hsc_s', 'degree_p', 'degree_t',
       'workex', 'etest_p', 'specialisation', 'mba_p', 'status', 'salary'],
      dtype='object')

In [108]:
df.dtypes

ssc_p             float64
ssc_b              object
hsc_p             float64
hsc_b              object
hsc_s              object
degree_p          float64
degree_t           object
workex             object
etest_p           float64
specialisation     object
mba_p             float64
status             object
salary            float64
dtype: object

In [109]:
df['workex'] = df['workex'].map({'Yes': 1, 'No': 0})
df['status'] = df['status'].map({'Placed': 1, 'Not Placed': 0})

In [110]:
df.drop(['ssc_b', 'hsc_b'], axis=1, inplace=True)

In [111]:
df.columns

Index(['ssc_p', 'hsc_p', 'hsc_s', 'degree_p', 'degree_t', 'workex', 'etest_p',
       'specialisation', 'mba_p', 'status', 'salary'],
      dtype='object')

Why One-Hot Encoding?
No false ranking (important!)
Better model performance
Safe for ML models

In [112]:
df = pd.get_dummies(df, columns=['degree_t', 'specialisation' , 'hsc_s'], drop_first=True)

print(df.head())

   ssc_p  hsc_p  degree_p  workex  etest_p  mba_p  status    salary  \
0  67.00  91.00     58.00       0     55.0  58.80       1  270000.0
1  79.33  78.33     77.48       1     86.5  66.28       1  200000.0
2  65.00  68.00     64.00       0     75.0  57.80       1  250000.0
3  56.00  52.00     52.00       0     66.0  59.43       0       NaN
4  85.80  73.60     73.30       0     96.8  55.50       1  425000.0

   degree_t_Others  degree_t_Sci&Tech  specialisation_Mkt&HR  hsc_s_Commerce  \
0            False               True                   True            True
1            False               True                  False           False
2            False              False                  False           False
3            False               True                   True           False
4            False              False                  False            True

   hsc_s_Science
0          False
1           True
2          False
3           True
4          False

In [113]:
df['overall_score'] = (df['ssc_p'] + df['hsc_p'] + df['degree_p'] + df['mba_p']) / 4

In [114]:
df['is_high_aptitude'] = df['etest_p'].apply(lambda x: 1 if x > 70 else 0)

Define Features & Target

In [115]:
X = df.drop(['status', 'salary'], axis=1)
y = df['status']

In [116]:
df.dtypes

ssc_p                    float64
hsc_p                    float64
degree_p                 float64
workex                     int64
etest_p                  float64
mba_p                    float64
status                     int64
salary                   float64
degree_t_Others             bool
degree_t_Sci&Tech           bool
specialisation_Mkt&HR       bool
hsc_s_Commerce              bool
hsc_s_Science               bool
overall_score            float64
is_high_aptitude           int64
dtype: object

In [117]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.6744186046511628

In [119]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [120]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [121]:
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.8604651162790697

Salary Prediction (Linear Regression)

In [122]:
# take only placed students
df_salary = df[df['status'] == 1]

X_sal = df_salary.drop(['status', 'salary'], axis=1)
y_sal = df_salary['salary']

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

X_train_s, X_test_s, y_train_s, y_test_s = train_test_split(X_sal, y_sal, test_size=0.2, random_state=42)

model_sal = LinearRegression()
model_sal.fit(X_train_s, y_train_s)

y_pred_s = model_sal.predict(X_test_s)

from sklearn.metrics import r2_score
print("R2 Score:", r2_score(y_test_s, y_pred_s))

R2 Score: -0.07775783528585012

In [123]:
df['readiness_score'] = (
    0.4 * df['overall_score'] +
    0.3 * df['etest_p'] +
    0.3 * (df['workex'] * 100)
)

In [124]:
def readiness_level(score):
    if score >= 75:
        return "High"
    elif score >= 60:
        return "Medium"
    else:
        return "Low"

df['readiness_level'] = df['readiness_score'].apply(readiness_level)

In [125]:
df = pd.get_dummies(df, columns=['readiness_level'], drop_first=True)

In [126]:
def risk_level(score):
    if score < 60:
        return "High Risk"
    elif score < 75:
        return "Medium Risk"
    else:
        return "Low Risk"

df['risk_level'] = df['readiness_score'].apply(risk_level)

In [127]:
df = pd.get_dummies(df, columns=['risk_level'], drop_first=True)

In [128]:
def student_analysis(pred, readiness, risk):

    # placement message
    if pred == 1:
        placement = "High Probability of Placement"
    else:
        placement = "Low Probability of Placement"

    # readiness message + motivation
    if readiness == "High":
        readiness_msg = "You are well-prepared and ready to grab opportunities."
        motivation = "Keep pushing forward — success is within your reach!"
    elif readiness == "Medium":
        readiness_msg = "You are on the right track but there is room for improvement."
        motivation = "Stay consistent and keep improving — you’re closer than you think!"
    else:
        readiness_msg = "You need to work on your skills and preparation."
        motivation = "Don’t give up — every expert was once a beginner. Start improving today!"

    # risk message
    if risk == "Low Risk":
        risk_msg = "Low risk — your profile is strong."
    elif risk == "Medium Risk":
        risk_msg = "Moderate risk — focus on improving key areas."
    else:
        risk_msg = "High risk — immediate improvement is required to boost your chances."

    # final output
    return f"""
🔹 Placement Prediction: {placement}
🔹 Readiness Level: {readiness}
🔹 Risk Level: {risk}

📊 Analysis:
{readiness_msg}
{risk_msg}

💡 Motivation:
{motivation}
"""